[package]
name = "multi-platform-screen-grabbing-utility"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Per la cattura dello schermo
scrap = "0.5.0"
# Per l'elaborazione delle immagini
image = "0.24.7"
# Per l'interfaccia utente
iced = "0.10.0"
# Per la gestione dei tasti di scelta rapida
hotkey-rs = "0.1.2"